id = "quasarized"
name = "Quasarized"
version = "0.0.2"
schema_version = 1
authors = ["shnarazk"]
description = "A modified color scheme based on Solarized with 4 additional colors for better readability. Features types in Orange, functions in Violet, and variables in Cyan."
repository = "https://github.com/shnarazk/Quasarized.Zed"
